    destination: ./_site
    lsi:         false
    port:        4000
    highlighter:  'pygments'
    permalink:   date
    name: Tormod Bøe
    description: Web log by Tormod Bøe
    url: http://tormodb.github.io
    safe: true
    markdown: redcarpet
    redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
